// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeJ9-hSrkcKlAdl1aNXAw3jFMACYYduA4',
    appId: '1:47600970379:android:d8261eb6dea31ca9cb828e',
    messagingSenderId: '47600970379',
    projectId: 'chatrix-c3809',
    storageBucket: 'chatrix-c3809.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMc7SUnuXaU4aIjgMq_BJbBPpnASITZuU',
    appId: '1:47600970379:ios:3c9af91e3ed5d04bcb828e',
    messagingSenderId: '47600970379',
    projectId: 'chatrix-c3809',
    storageBucket: 'chatrix-c3809.firebasestorage.app',
    androidClientId: '47600970379-2a5q7bl1g16v6tbtnsbfc629ib0eonoq.apps.googleusercontent.com',
    iosClientId: '47600970379-5hie2ecvtjoqou7kmdmd5vm97mk50o5f.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatrixAi',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGXBmiklhYxIKOwX3vfM6wi4waCz6mDm8',
    appId: '1:47600970379:web:766c326ee2695ebbcb828e',
    messagingSenderId: '47600970379',
    projectId: 'chatrix-c3809',
    authDomain: 'chatrix-c3809.firebaseapp.com',
    storageBucket: 'chatrix-c3809.firebasestorage.app',
    measurementId: 'G-DCSESR02E0',
  );

}